name: superblob
channels:
  - conda-forge
dependencies:
  - python=3.11
  - selenium
  - webdriver-manager
  - pytorch
  - torchvision
  - pyarrow<21.0.0
  - plotly
  - openai
  - streamlit
  - sentence-transformers
  - google-genai
  - undetected-chromedriver
  - html2text
  - pandas
  - markdownify
  - bs4
